/*
This is a future CS File that will remain mostly unused until the entire game is complete or 
most of the game//the part that completes it 




For now this has no use
*/


namespace Neoa
{

    public class YourHome
    {
        public bool YourHome = false;
        public bool DreamEnd = false;


        
        string Dreamer;
    
        public static void Intro()
        {
            Program.DisplayLine("..What is this.....?");
            Program.DisplayLine("Who are you....");
            Dreamer = Console.ReadLine();
            
        } 

    
    }
/*
The kings court is a DLC that is completely seperate from the base game.
*/
    public class TKC
    {
        public bool TKC = false
     while(TKC = true)
     {

     }

    }
}